// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: AddProductToCart.sql

package eshop

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProductToCart = `-- name: AddProductToCart :exec
INSERT INTO cart (
    customer_id,
    product_id,
    inserted_at
) VALUES
    ($1, $2, $3)
`

type AddProductToCartParams struct {
	CustomerID uuid.UUID
	ProductID  uuid.UUID
	InsertedAt time.Time
}

func (q *Queries) AddProductToCart(ctx context.Context, arg AddProductToCartParams) error {
	_, err := q.db.ExecContext(ctx, addProductToCart, arg.CustomerID, arg.ProductID, arg.InsertedAt)
	return err
}
