// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: CreateCustomer.sql

package eshop

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customer (
    id,
    name,
    email,
    created_at,
    updated_at
) VALUES
    ($1, $2, $3, $4, $5)
RETURNING id, name, email, created_at, updated_at
`

type CreateCustomerParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
