// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package eshop

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	CustomerID uuid.UUID
	ProductID  uuid.UUID
	InsertedAt time.Time
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CustomerAddress struct {
	ID           uuid.UUID
	CustomerID   uuid.UUID
	LocationName string
	Address      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       float64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
